branches:
only:
  - master
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - make all
after_success: coveralls
sudo: false
script: nosetests --with-coverage --cover-package=probablepeople
deploy:
  provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: d29239p1FSbCuW9v5cnxRbKUPidAD0GosW6HtUF2LIVO0epLPCHlOpG/REpnxYv5f/Ug0rL2luzglcpCb9ZqrRZw0WhzQAX3GT4qlYQ88xiVYYRErYbMnkP0l4Suls3IWmQ13Y5xwe8rDRwyHdL8rhJZmq358YnpiI7/2fYHoEs=
